"""strings begin"""
T_USERINFOS = 'userinfos'
T_USERINFOID = 'userinfoId'
T_USERINFOCOUNT = 'userinfoCount'
T_TOPICS = 'topics'
T_TOPICID = 'topicId'
T_TOPICCOUNT = 'topicCount'
T_SURVEYS = 'surveys'
T_SURVEYID = 'surveyId'
T_SURVEYCOUNT = 'surveyCount'
T_QUESTIONS = 'questions'
T_QUESTIONID = 'questionId'
T_QUESTIONCOUNT = 'questionCount'
T_OPTIONS = 'options'
T_OPTIONID = 'optionId'
T_OPTIONCOUNT = 'optionCount'
T_VISITS = 'visits'
T_VISITID = 'visitId'
T_VISITCOUNT = 'visitCount'
T_COMMITS = 'commits'
T_COMMITID = 'commitId'
T_COMMITCOUNT = 'commitCount'
T_ANSWERS = 'answers'
T_ANSWERID = 'answerId'
T_ANSWERCOUNT = 'answerCount'


T_ID = 'id'
T_TITLE = 'title'
T_DESCRIPTION = 'description'
T_CREATETIME= 'createTime'
T_PUBLISHTIME = 'publishTime'
T_CLOSETIME = 'closeTime'
T_STATUS = 'status'
T_REALNAME = 'realName'
T_USERNAME = 'userName'
T_PASSWORD = 'password'
T_EMAIL = 'email'
T_IMGURL = 'imgUrl'
T_ISPUBLIC = 'isPublic'
T_STAR = 'star'
T_ALLOWANONYMOUS = 'allowAnonymous'
T_IPRECORD = 'ipRecord'
T_USERNAMERECORD = 'userNameRecord'
T_REALNAMEINPUT = 'realNameInput'
T_MOBILEINPUT = 'mobileInput'
T_EMAILINPUT = 'emailInput'
T_ORDERINDEX = 'orderIndex'
T_NOTEMPTY = 'notEmpty'
T_RANDOMORDER = 'randomOrder'
T_MINVALUE = 'minValue'
T_MAXVALUE = 'maxValue'
T_TYPE = 'type'
T_ALLOWINPUT = 'allowInput'
T_RATE = 'rate'
T_IPADDR = 'ipAddr'
T_REFERER = 'referer'
T_TIMEUSESEC = 'timeUseSec'
T_MOBILE = 'mobile'

T_SUCCESS = 'success'
T_MESSAGE = 'message'
T_CONTENT = 'content'

T_FLAG = 'flag'
T_KEYWORD = 'keyword'

"""strings end"""